source 'https://svrgitpub.sdos.es/iOS/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_modular_headers!
inhibit_all_warnings!

def shared_pods
	pod 'SDOSSwiftExtension', :path => '../../'
    pod 'SDOSVIPER'
end

target :SDOSSwiftExtensionSample do
	shared_pods
end
